version: '2'
services:
  base:
    image: node:10
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/
  install:
    extends:
      service: base
    command: npm install
  build:
    extends:
      service: base
    command: npm start
  create-bundles:
    extends:
      service: base
    command: npm run create-bundles